apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-b-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AMOlmedo/infra-gitops.git
    targetRevision: main
    path: charts/service-b
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
